### ISSUE TITLE
Post Launch TODOs / Feature Ideas

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#22]
## Overview
Just tracking some things that if there is time would great to get in time for v1, otherwise can be fast follows.

## Features
1. [x] Image Gallery page - #84 
1. [x] "On the Air" banner - #85
1. [x] have footer social icons colors change color on hover (YT - red, Facebook - Blue, etc) - #67 

## Chores
1. [x] Publish Storybook to GH Pages - #86
1. [x] Upgrade latest Greenwood for https://github.com/ProjectEvergreen/greenwood/issues/581 - #76 
1. [x] Storybook hot reloading + `customElements.define` error - #87
    <details>
      <img src="https://user-images.githubusercontent.com/895923/194729239-51e366c1-f923-4f61-bfb6-ae49280cb514.png"/>
    </details>
1. [x] Tailwind 3.x <> Storybook (chore) - #88 
    - https://github.com/tailwindlabs/tailwindcss/issues/6314
    - https://stackoverflow.com/questions/71329335/how-to-setup-storybook-with-tailwindcss-reactjs-and-typescript
    - https://stackoverflow.com/questions/68020712/tailwind-css-classes-not-showing-in-storybook-build/70805809#70805809

**Comment by thescientist13** [comment]
all captured!
